create table public.final_cadastro_SIAPE (
	id_servidor_portal int null,
	nome varchar (200) null,
	cpf varchar (15) null,
	matricula varchar (10) null,
	descricao_cargo varchar (200) null,
	classe_cargo varchar (2) null,
	referencia_cargo varchar(5) null,
	padrao_cargo varchar (5) null,
	nivel_cargo varchar (200) null,
	sigla_funcao varchar (5) null,
	nivel_funcao varchar (5) null,
	funcao varchar (200) null,
	codigo_atividade varchar (50) null,
	atividade varchar (50) null,
	opcao_parcial varchar (200) null,
	cod_uorg_lotacao bigint null,
	uorg_lotacao varchar (200) null,
	cod_org_lotacao int null,
	org_lotacao varchar (200) null,
	cod_orgsup_lotacao int null,
	orgsup_lotacao varchar (100) null,
	cod_uorg_exercicio bigint null,
	uorg_exercicio varchar (200) null,
	cod_org_exercicio int null,
	org_exercicio varchar (200) null,
	cod_orgsup_exercicio int null,
	orgsup_exercicio varchar (200) null,
	cod_tipo_vinculo int null,
	tipo_vinculo varchar (50) null,
	situacao_vinculo varchar (50) null,
	data_inicio_afastamento date null,
	data_termino_afastamento date null,
	regime_juridico varchar (100) null,
	jornada_de_trabalho varchar (100) null,
	data_ingresso_cargofuncao date null,
	data_nomeacao_cargofuncao date null,
	data_ingresso_orgao date null,
	documento_ingresso_servicopublico varchar(10) null,
	data_diploma_ingresso_servicopublico date NULL,
	diploma_ingresso_cargofuncao varchar (50) NULL,
	diploma_ingresso_orgao varchar (50) NULL,
	diploma_ingresso_servicopublico varchar (50) NULL,
	uf_exercicio varchar(2) NULL
);