create table tmp_remuneracao_SIAPE (
	ano integer null,
	mes integer null,
	id_servidor_portal varchar(200) null,
	cpf varchar(200) null,
	nome varchar(200) null,
	remuneração_básica_bruta varchar(200) null,
	remuneração_básica_bruta_dolar varchar(200) null,
	abateteto varchar(200) null,
	abateteto_dolar varchar(200) null,
	gratificação_natalina varchar(200) null,
	gratificação_natalina_dolar varchar(200) null,
	abateteto_da_gratificação_natalina varchar(200) null,
	abateteto_da_gratificação_natalina_dolar varchar(200) null,
	férias varchar(200) null,
	férias_dolar varchar(200) null,
	outras_remunerações_eventuais varchar(200) null,
	outras_remunerações_eventuais_dolar varchar(200) null,
	irrf varchar(200) null,
	irrf_dolar varchar(200) null,
	pss_rpgs varchar(200) null,
	pss_rpgs_dolar varchar(200) null,
	demais_deduções varchar(200) null,
	demais_deduções_dolar varchar(200) null,
	pensão_militar varchar(200) null,
	pensão_militar_dolar varchar(200) null,
	fundo_de_saúde varchar(200) null,
	fundo_de_saúde_dolar varchar(200) null,
	taxa_de_ocupação_imóvel_funcional varchar(200) null,
	taxa_de_ocupação_imóvel_funcional_dolar varchar(200) null,
	remuneração_após_deduções_obrigatórias varchar(200) null,
	remuneração_após_deduções_obrigatórias_dolar varchar(200) null,
	verbas_indenizatórias_civil varchar(200) null,
	verbas_indenizatórias_civil_dolar varchar(200) null,
	verbas_indenizatórias_militar varchar(200) null,
	verbas_indenizatórias_militar_dolar varchar(200) null,
	verbas_indenizatórias_programa_desligamento_792_2017 varchar(200) null,
	verbas_indenizatórias_programa_desligamento_792_2017_dolar varchar(200) null,
	total_de_verbas_indenizatórias varchar(200) null,
	total_de_verbas_indenizatórias_dolar varchar(200) null
);
create table final_remuneracao_SIAPE (
	ano int null,
	mes int null,
	id_servidor_portal int null,
	cpf varchar(14) null,
	nome varchar(200) null,
	remuneração_após_deduções_obrigatórias decimal (15,2) null,
	remuneração_após_deduções_obrigatórias_dolar decimal (15,2) null,
	total_de_verbas_indenizatórias decimal (15,2) null,
	total_de_verbas_indenizatórias_dolar decimal (15,2) null
);
insert into final_remuneracao_SIAPE
select
	ano,
	mes,
	cast (id_servidor_portal as int),
	cpf,
	nome,
	cast (remuneração_após_deduções_obrigatórias as decimal (15,2)),
	cast (remuneração_após_deduções_obrigatórias_dolar as decimal (15,2)),
	cast (total_de_verbas_indenizatórias as decimal (15,2)),
	cast (total_de_verbas_indenizatórias_dolar as decimal (15,2))
from tmp_remuneracao_siape;