create table public.tmp_cadastro_SIAPE (
	id_servidor_portal varchar (1024) null,
	nome varchar (200) null,
	cpf varchar (200) null,
	matricula varchar (200) null,
	descricao_cargo varchar (200) null,
	classe_cargo varchar (2) null,
	referencia_cargo varchar(5) null,
	padrao_cargo varchar (5) null,
	nivel_cargo varchar (200) null,
	sigla_funcao varchar (200) null,
	nivel_funcao varchar (200) null,
	funcao varchar (200) null,
	codigo_atividade varchar (200) null,
	atividade varchar (200) null,
	opcao_parcial varchar (200) null,
	cod_uorg_lotacao varchar (200) null,
	uorg_lotacao varchar (200) null,
	cod_org_lotacao varchar (200) null,
	org_lotacao varchar (200) null,
	cod_orgsup_lotacao varchar (200) null,
	orgsup_lotacao varchar (200) null,
	cod_uorg_exercicio varchar (200) null,
	uorg_exercicio varchar (200) null,
	cod_org_exercicio varchar (200) null,
	org_exercicio varchar (200) null,
	cod_orgsup_exercicio varchar (200) null,
	orgsup_exercicio varchar (200) null,
	cod_tipo_vinculo varchar (200) null,
	tipo_vinculo varchar (200) null,
	situacao_vinculo varchar (200) null,
	data_inicio_afastamento varchar (200) null,
	data_termino_afastamento varchar (200) null,
	regime_juridico varchar (200) null,
	jornada_de_trabalho varchar (200) null,
	data_ingresso_cargofuncao varchar (200) null,
	data_nomeacao_cargofuncao varchar (200) null,
	data_ingresso_orgao varchar (200) null,
	documento_ingresso_servicopublico varchar(200) null,
	data_diploma_ingresso_servicopublico varchar (50) NULL,
	diploma_ingresso_cargofuncao varchar (20) NULL,
	diploma_ingresso_orgao varchar (20) NULL,
	diploma_ingresso_servicopublico varchar (20) NULL,
	uf_exercicio varchar(2) NULL
);
create table public.final_cadastro_SIAPE (
	id_servidor_portal int null,
	nome varchar (200) null,
	cpf varchar (15) null,
	matricula varchar (10) null,
	descricao_cargo varchar (200) null,
	classe_cargo varchar (2) null,
	referencia_cargo varchar(5) null,
	padrao_cargo varchar (5) null,
	nivel_cargo varchar (200) null,
	sigla_funcao varchar (5) null,
	nivel_funcao varchar (5) null,
	funcao varchar (200) null,
	codigo_atividade varchar (50) null,
	atividade varchar (50) null,
	opcao_parcial varchar (200) null,
	cod_uorg_lotacao bigint null,
	uorg_lotacao varchar (200) null,
	cod_org_lotacao int null,
	org_lotacao varchar (200) null,
	cod_orgsup_lotacao int null,
	orgsup_lotacao varchar (100) null,
	cod_uorg_exercicio bigint null,
	uorg_exercicio varchar (200) null,
	cod_org_exercicio int null,
	org_exercicio varchar (200) null,
	cod_orgsup_exercicio int null,
	orgsup_exercicio varchar (200) null,
	cod_tipo_vinculo int null,
	tipo_vinculo varchar (50) null,
	situacao_vinculo varchar (50) null,
	data_inicio_afastamento date null,
	data_termino_afastamento date null,
	regime_juridico varchar (100) null,
	jornada_de_trabalho varchar (100) null,
	data_ingresso_cargofuncao date null,
	data_nomeacao_cargofuncao date null,
	data_ingresso_orgao date null,
	documento_ingresso_servicopublico varchar(10) null,
	data_diploma_ingresso_servicopublico date NULL,
	diploma_ingresso_cargofuncao varchar (50) NULL,
	diploma_ingresso_orgao varchar (50) NULL,
	diploma_ingresso_servicopublico varchar (50) NULL,
	uf_exercicio varchar(2) NULL
);
insert into public.final_cadastro_SIAPE 
select
	cast (id_servidor_portal as int),
	nome,
	cpf,
	matricula,
	descricao_cargo,
	classe_cargo,
	referencia_cargo,
	padrao_cargo,
	nivel_cargo,
	sigla_funcao,
	nivel_funcao,
	funcao,
	codigo_atividade,
	atividade,
	opcao_parcial,
	cast (cod_uorg_lotacao as bigint),
	uorg_lotacao,
	cast (cod_org_lotacao as int),
	org_lotacao,
	cast (cod_orgsup_lotacao as int),
	orgsup_lotacao,
	cast (cod_uorg_exercicio as bigint),
	uorg_exercicio,
	cast (cod_org_exercicio as int),
	org_exercicio,
	cast (cod_orgsup_exercicio as int),
	orgsup_exercicio,
	cast (cod_tipo_vinculo as int),
	tipo_vinculo,
	situacao_vinculo,
	to_date (data_inicio_afastamento, 'dd/mm/yyyy'),
	to_date (data_termino_afastamento, 'dd/mm/yyyy'),
	regime_juridico,
	jornada_de_trabalho,
	to_date (data_ingresso_cargofuncao, 'dd/mm/yyyy'),
	to_date (data_nomeacao_cargofuncao, 'dd/mm/yyyy'),
	to_date (data_ingresso_orgao, 'dd/mm/yyyy'),
	documento_ingresso_servicopublico,
	to_date (data_diploma_ingresso_servicopublico, 'dd/mm/yyyy'),
	diploma_ingresso_cargofuncao,
	diploma_ingresso_orgao,
	diploma_ingresso_servicopublico,
	uf_exercicio
from tmp_cadastro_siape;